# Snapshot file
# Unset all aliases to avoid conflicts with functions
unalias -a 2>/dev/null || true
# Functions
eval "$(echo 'Y2xlYXJMbW9kICgpIAp7IAogICAgbW9kdWxlIC0tZm9yY2UgcHVyZ2U7CiAgICBldmFsICQoJExN
T0RfRElSL2NsZWFyTE1PRF9jbWQgLS1zaGVsbCBiYXNoIC0tZnVsbCAiJEAiKQp9Cg==' | base64 -d)" > /dev/null 2>&1
eval "$(echo 'Y2xlYXJNVCAoKSAKeyAKICAgIGV2YWwgJCgkTE1PRF9ESVIvY2xlYXJMTU9EX2NtZCAtLXNoZWxs
IGJhc2ggLS1zaW1wbGUpCn0K' | base64 -d)" > /dev/null 2>&1
eval "$(echo 'Y29tbWFuZF9ub3RfZm91bmRfaGFuZGxlICgpIAp7IAogICAgbG9jYWwgcnVuY25mPTE7CiAgICBs
b2NhbCByZXR2YWw9MTI3OwogICAgW1sgJC0gPT0gKiJpIiogXV0gfHwgcnVuY25mPTA7CiAgICBb
WyAhIC1TIC9ydW4vZGJ1cy9zeXN0ZW1fYnVzX3NvY2tldCBdXSAmJiBydW5jbmY9MDsKICAgIFtb
ICEgLXggJy91c3IvbGliZXhlYy9wYWNrYWdla2l0ZCcgXV0gJiYgcnVuY25mPTA7CiAgICBbWyAt
biAke0NPTVBfQ1dPUkQtfSBdXSAmJiBydW5jbmY9MDsKICAgIFtbICEgLXggJy91c3IvbGliZXhl
Yy9way1jb21tYW5kLW5vdC1mb3VuZCcgXV0gJiYgcnVuY25mPTA7CiAgICBpZiBbICRydW5jbmYg
LWVxIDEgXTsgdGhlbgogICAgICAgICcvdXNyL2xpYmV4ZWMvcGstY29tbWFuZC1ub3QtZm91bmQn
ICIkQCI7CiAgICAgICAgcmV0dmFsPSQ/OwogICAgZWxzZQogICAgICAgIGlmIFtbIC1uICIke0JB
U0hfVkVSU0lPTi19IiBdXTsgdGhlbgogICAgICAgICAgICBwcmludGYgJ2Jhc2g6ICVzJXNcbicg
IiR7MTorJDE6IH0iICIkKGdldHRleHQgUGFja2FnZUtpdCAnY29tbWFuZCBub3QgZm91bmQnKSIg
MT4mMjsKICAgICAgICBmaTsKICAgIGZpOwogICAgcmV0dXJuICRyZXR2YWwKfQo=' | base64 -d)" > /dev/null 2>&1
eval "$(echo 'Z2F3a2xpYnBhdGhfYXBwZW5kICgpIAp7IAogICAgWyAteiAiJEFXS0xJQlBBVEgiIF0gJiYgQVdL
TElCUEFUSD1gZ2F3ayAnQkVHSU4ge3ByaW50IEVOVklST05bIkFXS0xJQlBBVEgiXX0nYDsKICAg
IGV4cG9ydCBBV0tMSUJQQVRIPSIkQVdLTElCUEFUSDokKiIKfQo=' | base64 -d)" > /dev/null 2>&1
eval "$(echo 'Z2F3a2xpYnBhdGhfZGVmYXVsdCAoKSAKeyAKICAgIHVuc2V0IEFXS0xJQlBBVEg7CiAgICBleHBv
cnQgQVdLTElCUEFUSD1gZ2F3ayAnQkVHSU4ge3ByaW50IEVOVklST05bIkFXS0xJQlBBVEgiXX0n
YAp9Cg==' | base64 -d)" > /dev/null 2>&1
eval "$(echo 'Z2F3a2xpYnBhdGhfcHJlcGVuZCAoKSAKeyAKICAgIFsgLXogIiRBV0tMSUJQQVRIIiBdICYmIEFX
S0xJQlBBVEg9YGdhd2sgJ0JFR0lOIHtwcmludCBFTlZJUk9OWyJBV0tMSUJQQVRIIl19J2A7CiAg
ICBleHBvcnQgQVdLTElCUEFUSD0iJCo6JEFXS0xJQlBBVEgiCn0K' | base64 -d)" > /dev/null 2>&1
eval "$(echo 'Z2F3a3BhdGhfYXBwZW5kICgpIAp7IAogICAgWyAteiAiJEFXS1BBVEgiIF0gJiYgQVdLUEFUSD1g
Z2F3ayAnQkVHSU4ge3ByaW50IEVOVklST05bIkFXS1BBVEgiXX0nYDsKICAgIGV4cG9ydCBBV0tQ
QVRIPSIkQVdLUEFUSDokKiIKfQo=' | base64 -d)" > /dev/null 2>&1
eval "$(echo 'Z2F3a3BhdGhfZGVmYXVsdCAoKSAKeyAKICAgIHVuc2V0IEFXS1BBVEg7CiAgICBleHBvcnQgQVdL
UEFUSD1gZ2F3ayAnQkVHSU4ge3ByaW50IEVOVklST05bIkFXS1BBVEgiXX0nYAp9Cg==' | base64 -d)" > /dev/null 2>&1
eval "$(echo 'Z2F3a3BhdGhfcHJlcGVuZCAoKSAKeyAKICAgIFsgLXogIiRBV0tQQVRIIiBdICYmIEFXS1BBVEg9
YGdhd2sgJ0JFR0lOIHtwcmludCBFTlZJUk9OWyJBV0tQQVRIIl19J2A7CiAgICBleHBvcnQgQVdL
UEFUSD0iJCo6JEFXS1BBVEgiCn0K' | base64 -d)" > /dev/null 2>&1
eval "$(echo 'Z2NsICgpIAp7IAogICAgZWNobyAiJCBnaCBhcGkgXCIvdXNlcnMvXCQoZ2ggYXBpIHVzZXIgLS1q
cSAubG9naW4pL2V2ZW50c1wiIC0tanEgJ1suW10gfCBzZWxlY3QoLnR5cGUgPT0gXCJJc3N1ZUNv
bW1lbnRFdmVudFwiKV1bMDo1XVtdIHwgXCJcXCguY3JlYXRlZF9hdCB8IHN0cnB0aW1lKFwiJVkt
JW0tJWRUJUg6JU06JVNaXCIpIHwgc3RyZnRpbWUoXCIlWS0lbS0lZCAlSTolTTolUyAlcCBFU1Qv
RURUXCIpKSAtIFxcKC5hY3Rvci5sb2dpbikgLSBcXCgucGF5bG9hZC5jb21tZW50Lmh0bWxfdXJs
KVwiJyI7CiAgICBlY2hvOwogICAgbG9jYWwgY29tbWVudF9kYXRhOwogICAgY29tbWVudF9kYXRh
PSQoZ2ggYXBpICIvdXNlcnMvJChnaCBhcGkgdXNlciAtLWpxIC5sb2dpbikvZXZlbnRzIiAtLWpx
ICdbLltdIHwgc2VsZWN0KC50eXBlID09ICJJc3N1ZUNvbW1lbnRFdmVudCIpXVswOjVdW10gfCAi
XCguY3JlYXRlZF9hdCB8IHN0cnB0aW1lKCIlWS0lbS0lZFQlSDolTTolU1oiKSB8IHN0cmZ0aW1l
KCIlWS0lbS0lZCAlSTolTTolUyAlcCBFU1QvRURUIikpIC0gXCguYWN0b3IubG9naW4pIC0gXCgu
cGF5bG9hZC5jb21tZW50Lmh0bWxfdXJsKSInKTsKICAgIGVjaG8gIiRjb21tZW50X2RhdGEiCn0K' | base64 -d)" > /dev/null 2>&1
eval "$(echo 'Z2V0X2dpdF9icmFuY2ggKCkgCnsgCiAgICBsb2NhbCBicmFuY2g9JChnaXQgYnJhbmNoIDI+IC9k
ZXYvbnVsbCB8IGdyZXAgJ14qJyB8IGN1dCAtZCcgJyAtZjItKTsKICAgIGlmIFsgLW4gIiRicmFu
Y2giIF07IHRoZW4KICAgICAgICBlY2hvICIgKCRicmFuY2gpIjsKICAgIGZpCn0K' | base64 -d)" > /dev/null 2>&1
eval "$(echo 'Z2V0X3Nob3J0X3BhdGggKCkgCnsgCiAgICBsb2NhbCBkaXI9JChwd2QgfCBzZWQgInN8JEhPTUV8
fnwiKTsKICAgIGxvY2FsIElGUz0nLyc7CiAgICBsb2NhbCBwYXRoX2FycmF5PSgkZGlyKTsKICAg
IGxvY2FsIGxlbj0keyNwYXRoX2FycmF5W0BdfTsKICAgIGlmIFsgJGxlbiAtZ3QgMyBdOyB0aGVu
CiAgICAgICAgZWNobyAiLi4uLyR7cGF0aF9hcnJheVskKChsZW4tMikpXX0vJHtwYXRoX2FycmF5
WyQoKGxlbi0xKSldfSI7CiAgICBlbHNlCiAgICAgICAgZWNobyAiJGRpciI7CiAgICBmaQp9Cg==' | base64 -d)" > /dev/null 2>&1
eval "$(echo 'Z2hpICgpIAp7IAogICAgVVJMPSQoZ2ggaXNzdWUgdmlldyAiJDEiIC0tanNvbiB1cmwgLXEgIi51
cmwiKTsKICAgIGVjaG8gIvCflJcgSXNzdWUgVVJMOiAkVVJMIjsKICAgIGVjaG8gIiRVUkwiIHwg
eGFyZ3MgeGRnLW9wZW4KfQo=' | base64 -d)" > /dev/null 2>&1
eval "$(echo 'Z2hwciAoKSAKeyAKICAgIFVSTD0kKGdoIHByIHZpZXcgIiQxIiAtLWpzb24gdXJsIC1xICIudXJs
Iik7CiAgICBlY2hvICLwn5SXIFBSIFVSTDogJFVSTCI7CiAgICBlY2hvICIkVVJMIiB8IHhhcmdz
IHhkZy1vcGVuCn0K' | base64 -d)" > /dev/null 2>&1
eval "$(echo 'Z2hwcnQgKCkgCnsgCiAgICBVUkw9JChnaCBwciB2aWV3ICIkMSIgLS1qc29uIHVybCAtcSAiLnVy
bCIpOwogICAgZWNobyAi8J+UlyBQUiBVUkw6ICRVUkwiOwogICAgZ2ggcHIgdmlldyAiJDEiIC0t
d2ViPWZhbHNlOwogICAgZWNobyAiUHJlc3MgRW50ZXIgdG8gb3BlbiBpbiBicm93c2VyLi4uIjsK
ICAgIHJlYWQgLXI7CiAgICB4ZGctb3BlbiAiJFVSTCIKfQo=' | base64 -d)" > /dev/null 2>&1
eval "$(echo 'Z3d0ICgpIAp7IAogICAgaWYgWyAteiAiJDEiIF07IHRoZW4KICAgICAgICBlY2hvICLinZcgVXNh
Z2U6IGd3dCA8YnJhbmNoLW5hbWU+IFstLW5vLXN5bmNdIjsKICAgICAgICBlY2hvICIgIENyZWF0
ZXMgd29ya3RyZWUgYW5kIHN5bmNzIHdpdGggdXBzdHJlYW0vbWFpbiBmaXJzdCAodW5sZXNzIC0t
bm8tc3luYykiOwogICAgICAgIHJldHVybiAxOwogICAgZmk7CiAgICBicmFuY2g9IiQxIjsKICAg
IG5vX3N5bmM9IiQyIjsKICAgIHJlcG9fcm9vdD0kKGdpdCByZXYtcGFyc2UgLS1zaG93LXRvcGxl
dmVsKTsKICAgIHdvcmt0cmVlX2Rpcj0iJHJlcG9fcm9vdC8ud29ya3RyZWVzLyRicmFuY2giOwog
ICAgaWYgWyAtZCAiJHdvcmt0cmVlX2RpciIgXTsgdGhlbgogICAgICAgIGVjaG8gIuKchSBXb3Jr
dHJlZSBhbHJlYWR5IGV4aXN0cywgb3BlbmluZy4uLiI7CiAgICAgICAgY3Vyc29yICIkd29ya3Ry
ZWVfZGlyIiAmIHJldHVybiAwOwogICAgZmk7CiAgICBta2RpciAtcCAiJHJlcG9fcm9vdC8ud29y
a3RyZWVzIjsKICAgIGlmIFsgIiRub19zeW5jIiAhPSAiLS1uby1zeW5jIiBdOyB0aGVuCiAgICAg
ICAgZWNobyAi8J+UhCBTeW5jaW5nIG1haW4gd2l0aCB1cHN0cmVhbS4uLiI7CiAgICAgICAgY3Vy
cmVudF9icmFuY2g9JChnaXQgcmV2LXBhcnNlIC0tYWJicmV2LXJlZiBIRUFEKTsKICAgICAgICBp
ZiAhIGdpdCBkaWZmLWluZGV4IC0tcXVpZXQgSEVBRCAtLTsgdGhlbgogICAgICAgICAgICBlY2hv
ICLwn5K+IFN0YXNoaW5nIGxvY2FsIGNoYW5nZXMuLi4iOwogICAgICAgICAgICBnaXQgc3Rhc2gg
cHVzaCAtbSAiZ3d0OiBhdXRvLXN0YXNoIGJlZm9yZSBzeW5jIjsKICAgICAgICAgICAgc3Rhc2hl
ZD10cnVlOwogICAgICAgIGZpOwogICAgICAgIGdpdCBjaGVja291dCBtYWluIDI+IC9kZXYvbnVs
bCB8fCBnaXQgY2hlY2tvdXQgbWFzdGVyIDI+IC9kZXYvbnVsbDsKICAgICAgICBlY2hvICLwn6e5
IFJlc2V0dGluZyBtYWluIHRvIGNsZWFuIHN0YXRlLi4uIjsKICAgICAgICBnaXQgcmVzZXQgLS1o
YXJkIEhFQUQ7CiAgICAgICAgZ2l0IGNsZWFuIC1mZDsKICAgICAgICBpZiBnaXQgcmVtb3RlIHwg
Z3JlcCAtcSB1cHN0cmVhbTsgdGhlbgogICAgICAgICAgICBnaXQgcHVsbCB1cHN0cmVhbSBtYWlu
IC0tcmViYXNlIDI+IC9kZXYvbnVsbCB8fCBnaXQgcHVsbCB1cHN0cmVhbSBtYXN0ZXIgLS1yZWJh
c2UgMj4gL2Rldi9udWxsOwogICAgICAgICAgICBnaXQgcHVzaCBvcmlnaW4gSEVBRCAyPiAvZGV2
L251bGwgfHwgdHJ1ZTsKICAgICAgICBlbHNlCiAgICAgICAgICAgIGdpdCBwdWxsIG9yaWdpbiAt
LXJlYmFzZTsKICAgICAgICBmaTsKICAgICAgICBnaXQgY2hlY2tvdXQgIiRjdXJyZW50X2JyYW5j
aCIgMj4gL2Rldi9udWxsIHx8IHRydWU7CiAgICAgICAgaWYgWyAiJHN0YXNoZWQiID0gdHJ1ZSBd
OyB0aGVuCiAgICAgICAgICAgIGVjaG8gIvCflIQgUmVzdG9yaW5nIHN0YXNoZWQgY2hhbmdlcy4u
LiI7CiAgICAgICAgICAgIGdpdCBzdGFzaCBwb3A7CiAgICAgICAgZmk7CiAgICBmaTsKICAgIGVj
aG8gIvCfjL8gQ3JlYXRpbmcgd29ya3RyZWUgZm9yIGJyYW5jaCAnJGJyYW5jaCcuLi4iOwogICAg
aWYgZ2l0IHNob3ctcmVmIC0tdmVyaWZ5IC0tcXVpZXQgInJlZnMvaGVhZHMvJGJyYW5jaCI7IHRo
ZW4KICAgICAgICBlY2hvICLwn5OMIFVzaW5nIGV4aXN0aW5nIGJyYW5jaCAnJGJyYW5jaCciOwog
ICAgICAgIGdpdCB3b3JrdHJlZSBhZGQgIiR3b3JrdHJlZV9kaXIiICIkYnJhbmNoIjsKICAgIGVs
c2UKICAgICAgICBpZiBnaXQgc2hvdy1yZWYgLS12ZXJpZnkgLS1xdWlldCAicmVmcy9yZW1vdGVz
L29yaWdpbi8kYnJhbmNoIjsgdGhlbgogICAgICAgICAgICBlY2hvICLwn5OlIENoZWNraW5nIG91
dCByZW1vdGUgYnJhbmNoICdvcmlnaW4vJGJyYW5jaCciOwogICAgICAgICAgICBnaXQgd29ya3Ry
ZWUgYWRkICIkd29ya3RyZWVfZGlyIiAtYiAiJGJyYW5jaCIgIm9yaWdpbi8kYnJhbmNoIjsKICAg
ICAgICBlbHNlCiAgICAgICAgICAgIGVjaG8gIuKcqCBDcmVhdGluZyBuZXcgYnJhbmNoICckYnJh
bmNoJyBmcm9tIG1haW4iOwogICAgICAgICAgICBtYWluX2JyYW5jaD0kKGdpdCBzeW1ib2xpYy1y
ZWYgcmVmcy9yZW1vdGVzL29yaWdpbi9IRUFEIDI+IC9kZXYvbnVsbCB8IHNlZCAnc0BecmVmcy9y
ZW1vdGVzL29yaWdpbi9AQCcgfHwgZWNobyAibWFpbiIpOwogICAgICAgICAgICBnaXQgd29ya3Ry
ZWUgYWRkICIkd29ya3RyZWVfZGlyIiAtYiAiJGJyYW5jaCIgIiRtYWluX2JyYW5jaCI7CiAgICAg
ICAgZmk7CiAgICBmaTsKICAgIGlmIFsgLWYgIiRyZXBvX3Jvb3QvLmN1cnNvci9ydWxlcy5tZCIg
XTsgdGhlbgogICAgICAgIGVjaG8gIvCfk5wgQ29weWluZyAuY3Vyc29yL3J1bGVzLm1kIGludG8g
bmV3IHdvcmt0cmVlIjsKICAgICAgICBta2RpciAtcCAiJHdvcmt0cmVlX2Rpci8uY3Vyc29yIjsK
ICAgICAgICBjcCAiJHJlcG9fcm9vdC8uY3Vyc29yL3J1bGVzLm1kIiAiJHdvcmt0cmVlX2Rpci8u
Y3Vyc29yL3J1bGVzLm1kIjsKICAgIGZpOwogICAgaWYgWyAtZiAiJEhPTUUvLmN1cnNvci9TdXBl
cl9DbGF1ZGVfRG9jcy5tZCIgXTsgdGhlbgogICAgICAgIGVjaG8gIvCfk5wgQ29weWluZyBTdXBl
cl9DbGF1ZGVfRG9jcy5tZCBpbnRvIG5ldyB3b3JrdHJlZSI7CiAgICAgICAgbWtkaXIgLXAgIiR3
b3JrdHJlZV9kaXIvLmN1cnNvciI7CiAgICAgICAgY3AgIiRIT01FLy5jdXJzb3IvU3VwZXJfQ2xh
dWRlX0RvY3MubWQiICIkd29ya3RyZWVfZGlyLy5jdXJzb3IvU3VwZXJfQ2xhdWRlX0RvY3MubWQi
OwogICAgZmk7CiAgICBlY2hvICLwn5qAIE9wZW5pbmcgd29ya3RyZWUgaW4gQ3Vyc29yLi4uIjsK
ICAgIGN1cnNvciAiJHdvcmt0cmVlX2RpciIgJgp9Cg==' | base64 -d)" > /dev/null 2>&1
eval "$(echo 'Z3d0LWNsZWFuICgpIAp7IAogICAgZ2l0IHdvcmt0cmVlIHBydW5lCn0K' | base64 -d)" > /dev/null 2>&1
eval "$(echo 'Z3d0LWxpc3QgKCkgCnsgCiAgICBnaXQgd29ya3RyZWUgbGlzdAp9Cg==' | base64 -d)" > /dev/null 2>&1
eval "$(echo 'Z3d0LXByICgpIAp7IAogICAgYnJhbmNoPSQoZ2l0IHJldi1wYXJzZSAtLWFiYnJldi1yZWYgSEVB
RCk7CiAgICBlY2hvICLwn5OdIENyZWF0aW5nIGRyYWZ0IFBSIGZvciBicmFuY2ggJyRicmFuY2gn
Li4uIjsKICAgIGdoIHByIGNyZWF0ZSAtLWZpbGwgLS1kcmFmdCAtLWhlYWQgIiRicmFuY2giIC0t
d2ViCn0K' | base64 -d)" > /dev/null 2>&1
eval "$(echo 'Z3d0LXB1c2ggKCkgCnsgCiAgICBicmFuY2g9JChnaXQgcmV2LXBhcnNlIC0tYWJicmV2LXJlZiBI
RUFEKTsKICAgIHJlbW90ZV9icmFuY2hfZXhpc3RzPSQoZ2l0IGxzLXJlbW90ZSAtLWhlYWRzIG9y
aWdpbiAiJGJyYW5jaCIpOwogICAgaWYgWyAteiAiJHJlbW90ZV9icmFuY2hfZXhpc3RzIiBdOyB0
aGVuCiAgICAgICAgZWNobyAi8J+agCBQdXNoaW5nIG5ldyBicmFuY2ggJyRicmFuY2gnIHRvIG9y
aWdpbi4uLiI7CiAgICAgICAgZ2l0IHB1c2ggLS1zZXQtdXBzdHJlYW0gb3JpZ2luICIkYnJhbmNo
IjsKICAgIGVsc2UKICAgICAgICBlY2hvICLwn5OkIFB1c2hpbmcgY2hhbmdlcyB0byBleGlzdGlu
ZyBicmFuY2ggJyRicmFuY2gnLi4uIjsKICAgICAgICBnaXQgcHVzaDsKICAgIGZpCn0K' | base64 -d)" > /dev/null 2>&1
eval "$(echo 'Z3d0LXJtICgpIAp7IAogICAgaWYgWyAteiAiJDEiIF07IHRoZW4KICAgICAgICBlY2hvICLinZcg
VXNhZ2U6IGd3dC1ybSA8YnJhbmNoLW5hbWU+IjsKICAgICAgICByZXR1cm4gMTsKICAgIGZpOwog
ICAgcmVwb19yb290PSQoZ2l0IHJldi1wYXJzZSAtLXNob3ctdG9wbGV2ZWwpOwogICAgZ2l0IHdv
cmt0cmVlIHJlbW92ZSAiJHJlcG9fcm9vdC8ud29ya3RyZWVzLyQxIgp9Cg==' | base64 -d)" > /dev/null 2>&1
eval "$(echo 'Z3d0LXN5bmMgKCkgCnsgCiAgICBsb2NhbCBmb3JjZV9wdXNoPSIkMSI7CiAgICBsb2NhbCBjdXJy
ZW50X2JyYW5jaD0kKGdpdCByZXYtcGFyc2UgLS1hYmJyZXYtcmVmIEhFQUQpOwogICAgaWYgW1sg
IiRjdXJyZW50X2JyYW5jaCIgPT0gIm1haW4iIHx8ICIkY3VycmVudF9icmFuY2giID09ICJtYXN0
ZXIiIF1dOyB0aGVuCiAgICAgICAgZWNobyAi4p2MIENhbm5vdCBzeW5jIG1haW4vbWFzdGVyIGJy
YW5jaC4gVXNlIHJlZ3VsYXIgZ2l0IHB1bGwgaW5zdGVhZC4iOwogICAgICAgIHJldHVybiAxOwog
ICAgZmk7CiAgICBlY2hvICLwn5SEIFN5bmNpbmcgYnJhbmNoICckY3VycmVudF9icmFuY2gnIHdp
dGggdXBzdHJlYW0uLi4iOwogICAgbG9jYWwgc3Rhc2hlZD1mYWxzZTsKICAgIGlmICEgZ2l0IGRp
ZmYtaW5kZXggLS1xdWlldCBIRUFEIC0tOyB0aGVuCiAgICAgICAgZWNobyAi8J+SviBTdGFzaGlu
ZyB1bmNvbW1pdHRlZCBjaGFuZ2VzLi4uIjsKICAgICAgICBnaXQgc3Rhc2ggcHVzaCAtbSAiZ3d0
LXN5bmM6IGF1dG8tc3Rhc2ggJChkYXRlKSI7CiAgICAgICAgc3Rhc2hlZD10cnVlOwogICAgZmk7
CiAgICBsb2NhbCBtYWluX2JyYW5jaD0kKGdpdCBzeW1ib2xpYy1yZWYgcmVmcy9yZW1vdGVzL29y
aWdpbi9IRUFEIDI+IC9kZXYvbnVsbCB8IHNlZCAnc0BecmVmcy9yZW1vdGVzL29yaWdpbi9AQCcg
fHwgZWNobyAibWFpbiIpOwogICAgZWNobyAi8J+TpSBGZXRjaGluZyBsYXRlc3QgY2hhbmdlcy4u
LiI7CiAgICBnaXQgZmV0Y2ggLS1hbGwgLS1wcnVuZTsKICAgIGlmIGdpdCByZW1vdGUgfCBncmVw
IC1xIHVwc3RyZWFtOyB0aGVuCiAgICAgICAgZWNobyAi8J+UhCBSZWJhc2luZyBvbiB1cHN0cmVh
bS8kbWFpbl9icmFuY2guLi4iOwogICAgICAgIGlmICEgZ2l0IHJlYmFzZSAidXBzdHJlYW0vJG1h
aW5fYnJhbmNoIjsgdGhlbgogICAgICAgICAgICBlY2hvICLimqDvuI8gIFJlYmFzZSBjb25mbGlj
dHMgZGV0ZWN0ZWQuIFJlc29sdmUgY29uZmxpY3RzIGFuZCBydW46IjsKICAgICAgICAgICAgZWNo
byAiICAgZ2l0IHJlYmFzZSAtLWNvbnRpbnVlIjsKICAgICAgICAgICAgZWNobyAiICAgVGhlbiBv
cHRpb25hbGx5OiBnd3Qtc3luYyAtLWZvcmNlLXdpdGgtbGVhc2UiOwogICAgICAgICAgICByZXR1
cm4gMTsKICAgICAgICBmaTsKICAgIGVsc2UKICAgICAgICBlY2hvICLwn5SEIFJlYmFzaW5nIG9u
IG9yaWdpbi8kbWFpbl9icmFuY2guLi4iOwogICAgICAgIGlmICEgZ2l0IHJlYmFzZSAib3JpZ2lu
LyRtYWluX2JyYW5jaCI7IHRoZW4KICAgICAgICAgICAgZWNobyAi4pqg77iPICBSZWJhc2UgY29u
ZmxpY3RzIGRldGVjdGVkLiBSZXNvbHZlIGNvbmZsaWN0cyBhbmQgcnVuOiI7CiAgICAgICAgICAg
IGVjaG8gIiAgIGdpdCByZWJhc2UgLS1jb250aW51ZSI7CiAgICAgICAgICAgIGVjaG8gIiAgIFRo
ZW4gb3B0aW9uYWxseTogZ3d0LXN5bmMgLS1mb3JjZS13aXRoLWxlYXNlIjsKICAgICAgICAgICAg
cmV0dXJuIDE7CiAgICAgICAgZmk7CiAgICBmaTsKICAgIGlmIFsgIiRzdGFzaGVkIiA9IHRydWUg
XTsgdGhlbgogICAgICAgIGVjaG8gIvCflIQgUmVzdG9yaW5nIHN0YXNoZWQgY2hhbmdlcy4uLiI7
CiAgICAgICAgaWYgISBnaXQgc3Rhc2ggcG9wOyB0aGVuCiAgICAgICAgICAgIGVjaG8gIuKaoO+4
jyAgU3Rhc2ggcG9wIGNvbmZsaWN0cy4gUmVzb2x2ZSBtYW51YWxseSB3aXRoOiBnaXQgc3Rhc2gg
bGlzdCI7CiAgICAgICAgZmk7CiAgICBmaTsKICAgIGxvY2FsIHJlbW90ZV9leGlzdHM9JChnaXQg
bHMtcmVtb3RlIC0taGVhZHMgb3JpZ2luICIkY3VycmVudF9icmFuY2giKTsKICAgIGlmIFsgLW4g
IiRyZW1vdGVfZXhpc3RzIiBdOyB0aGVuCiAgICAgICAgaWYgWyAiJGZvcmNlX3B1c2giID0gIi0t
Zm9yY2Utd2l0aC1sZWFzZSIgXSB8fCBbICIkZm9yY2VfcHVzaCIgPSAiLWYiIF07IHRoZW4KICAg
ICAgICAgICAgZWNobyAi8J+agCBGb3JjZSBwdXNoaW5nIHJlYmFzZWQgYnJhbmNoIHRvIG9yaWdp
bi4uLiI7CiAgICAgICAgICAgIGdpdCBwdXNoIC0tZm9yY2Utd2l0aC1sZWFzZSBvcmlnaW4gIiRj
dXJyZW50X2JyYW5jaCI7CiAgICAgICAgZWxzZQogICAgICAgICAgICBlY2hvICLwn5OkIENoZWNr
aW5nIGlmIHB1c2ggaXMgbmVlZGVkLi4uIjsKICAgICAgICAgICAgbG9jYWwgbG9jYWxfY29tbWl0
PSQoZ2l0IHJldi1wYXJzZSBIRUFEKTsKICAgICAgICAgICAgbG9jYWwgcmVtb3RlX2NvbW1pdD0k
KGdpdCByZXYtcGFyc2UgIm9yaWdpbi8kY3VycmVudF9icmFuY2giIDI+IC9kZXYvbnVsbCB8fCBl
Y2hvICIiKTsKICAgICAgICAgICAgaWYgWyAiJGxvY2FsX2NvbW1pdCIgIT0gIiRyZW1vdGVfY29t
bWl0IiBdOyB0aGVuCiAgICAgICAgICAgICAgICBlY2hvICLimqDvuI8gIEJyYW5jaCBoaXN0b3J5
IGhhcyBjaGFuZ2VkIGR1ZSB0byByZWJhc2UuIjsKICAgICAgICAgICAgICAgIGVjaG8gIvCfkqEg
VXNlICdnd3Qtc3luYyAtLWZvcmNlLXdpdGgtbGVhc2UnIHRvIHVwZGF0ZSByZW1vdGUgYnJhbmNo
IjsKICAgICAgICAgICAgICAgIGVjaG8gIiAgIE9yIG1hbnVhbGx5OiBnaXQgcHVzaCAtLWZvcmNl
LXdpdGgtbGVhc2Ugb3JpZ2luICRjdXJyZW50X2JyYW5jaCI7CiAgICAgICAgICAgIGVsc2UKICAg
ICAgICAgICAgICAgIGVjaG8gIuKchSBSZW1vdGUgYnJhbmNoIGlzIGFscmVhZHkgdXAgdG8gZGF0
ZSI7CiAgICAgICAgICAgIGZpOwogICAgICAgIGZpOwogICAgZWxzZQogICAgICAgIGVjaG8gIvCf
k6QgUHVzaGluZyBuZXcgYnJhbmNoIHRvIG9yaWdpbi4uLiI7CiAgICAgICAgZ2l0IHB1c2ggLS1z
ZXQtdXBzdHJlYW0gb3JpZ2luICIkY3VycmVudF9icmFuY2giOwogICAgZmk7CiAgICBlY2hvICLi
nIUgU3luYyBjb21wbGV0ZWQgZm9yIGJyYW5jaCAnJGN1cnJlbnRfYnJhbmNoJyIKfQo=' | base64 -d)" > /dev/null 2>&1
eval "$(echo 'bG1wciAoKSAKeyAKICAgIGxvY2FsIHByX251bWJlcj0kMTsKICAgIGlmIFsgLXogIiRwcl9udW1i
ZXIiIF07IHRoZW4KICAgICAgICBlY2hvICJVc2FnZTogbG1wciA8UFJfTlVNQkVSPiI7CiAgICAg
ICAgZWNobyAiRXhhbXBsZTogbG1wciAyOTkzIjsKICAgICAgICByZXR1cm4gMTsKICAgIGZpOwog
ICAgZWNobyAi8J+UjSBDaGVja2luZyBsbGFtYS1zdGFjayBQUiAjJHByX251bWJlci4uLiI7CiAg
ICBnaCBwciB2aWV3ICRwcl9udW1iZXIgLS1yZXBvIG1ldGEtbGxhbWEvbGxhbWEtc3RhY2sgLS1q
c29uIHRpdGxlLHN0YXRlLG1lcmdlYWJsZSxzdGF0dXNDaGVja1JvbGx1cDsKICAgIGVjaG8gLWUg
Ilxu8J+TiiBUZXN0IFN0YXR1czoiOwogICAgZ2ggcHIgY2hlY2tzICRwcl9udW1iZXIgLS1yZXBv
IG1ldGEtbGxhbWEvbGxhbWEtc3RhY2sKfQo=' | base64 -d)" > /dev/null 2>&1
eval "$(echo 'bWwgKCkgCnsgCiAgICBldmFsICIkKCRMTU9EX0RJUi9tbF9jbWQgIiRAIikiCn0K' | base64 -d)" > /dev/null 2>&1
eval "$(echo 'bW9kdWxlICgpIAp7IAogICAgaWYgWyAteiAiJHtMTU9EX1NIX0RCR19PTit4fSIgXTsgdGhlbgog
ICAgICAgIGNhc2UgIiQtIiBpbiAKICAgICAgICAgICAgKnYqeCopCiAgICAgICAgICAgICAgICBf
X2xtb2Rfc2hfZGJnPSd2eCcKICAgICAgICAgICAgOzsKICAgICAgICAgICAgKnYqKQogICAgICAg
ICAgICAgICAgX19sbW9kX3NoX2RiZz0ndicKICAgICAgICAgICAgOzsKICAgICAgICAgICAgKngq
KQogICAgICAgICAgICAgICAgX19sbW9kX3NoX2RiZz0neCcKICAgICAgICAgICAgOzsKICAgICAg
ICBlc2FjOwogICAgZmk7CiAgICBpZiBbIC1uICIke19fbG1vZF9zaF9kYmc6LX0iIF07IHRoZW4K
ICAgICAgICBzZXQgKyRfX2xtb2Rfc2hfZGJnOwogICAgICAgIGVjaG8gIlNoZWxsIGRlYnVnZ2lu
ZyB0ZW1wb3JhcmlseSBzaWxlbmNlZDogZXhwb3J0IExNT0RfU0hfREJHX09OPTEgZm9yIExtb2Qn
cyBvdXRwdXQiIDE+JjI7CiAgICBmaTsKICAgIGV2YWwgIiQoJExNT0RfQ01EIHNoZWxsICIkQCIp
IiAmJiBldmFsICIkKCR7TE1PRF9TRVRUQVJHX0NNRDotOn0gLXMgc2gpIjsKICAgIF9fbG1vZF9t
eV9zdGF0dXM9JD87CiAgICBpZiBbIC1uICIke19fbG1vZF9zaF9kYmc6LX0iIF07IHRoZW4KICAg
ICAgICBlY2hvICJTaGVsbCBkZWJ1Z2dpbmcgcmVzdGFydGVkIiAxPiYyOwogICAgICAgIHNldCAt
JF9fbG1vZF9zaF9kYmc7CiAgICBmaTsKICAgIHVuc2V0IF9fbG1vZF9zaF9kYmc7CiAgICByZXR1
cm4gJF9fbG1vZF9teV9zdGF0dXMKfQo=' | base64 -d)" > /dev/null 2>&1
eval "$(echo 'cHllbnYgKCkgCnsgCiAgICBsb2NhbCBjb21tYW5kPSR7MTotfTsKICAgIFsgIiQjIiAtZ3QgMCBd
ICYmIHNoaWZ0OwogICAgY2FzZSAiJGNvbW1hbmQiIGluIAogICAgICAgIGFjdGl2YXRlIHwgZGVh
Y3RpdmF0ZSB8IHJlaGFzaCB8IHNoZWxsKQogICAgICAgICAgICBldmFsICIkKHB5ZW52ICJzaC0k
Y29tbWFuZCIgIiRAIikiCiAgICAgICAgOzsKICAgICAgICAqKQogICAgICAgICAgICBjb21tYW5k
IHB5ZW52ICIkY29tbWFuZCIgIiRAIgogICAgICAgIDs7CiAgICBlc2FjCn0K' | base64 -d)" > /dev/null 2>&1
eval "$(echo 'eFNldFRpdGxlTG1vZCAoKSAKeyAKICAgIGJ1aWx0aW4gZWNobyAtbiAtZSAiXDAzM10yOyQxXDAw
NyIKfQo=' | base64 -d)" > /dev/null 2>&1
# Shell Options
shopt -u autocd
shopt -u assoc_expand_once
shopt -u cdable_vars
shopt -u cdspell
shopt -u checkhash
shopt -u checkjobs
shopt -s checkwinsize
shopt -s cmdhist
shopt -u compat31
shopt -u compat32
shopt -u compat40
shopt -u compat41
shopt -u compat42
shopt -u compat43
shopt -u compat44
shopt -s complete_fullquote
shopt -u direxpand
shopt -u dirspell
shopt -u dotglob
shopt -u execfail
shopt -u expand_aliases
shopt -u extdebug
shopt -u extglob
shopt -s extquote
shopt -u failglob
shopt -s force_fignore
shopt -s globasciiranges
shopt -s globskipdots
shopt -u globstar
shopt -u gnu_errfmt
shopt -s histappend
shopt -u histreedit
shopt -u histverify
shopt -s hostcomplete
shopt -u huponexit
shopt -u inherit_errexit
shopt -s interactive_comments
shopt -u lastpipe
shopt -u lithist
shopt -u localvar_inherit
shopt -u localvar_unset
shopt -s login_shell
shopt -u mailwarn
shopt -u no_empty_cmd_completion
shopt -u nocaseglob
shopt -u nocasematch
shopt -u noexpand_translation
shopt -u nullglob
shopt -s patsub_replacement
shopt -s progcomp
shopt -u progcomp_alias
shopt -s promptvars
shopt -u restricted_shell
shopt -u shift_verbose
shopt -s sourcepath
shopt -u syslog_history
shopt -u varredir_close
shopt -u xpg_echo
set -o braceexpand
set -o hashall
set -o interactive-comments
set -o monitor
set -o onecmd
shopt -s expand_aliases
# Aliases
alias -- c='clear'
alias -- cursor='/usr/local/sbin/cur'
alias -- egrep='grep -E --color=auto'
alias -- fgrep='grep -F --color=auto'
alias -- grep='grep --color=auto'
alias -- l='ls -CF'
alias -- la='ls -la'
alias -- ll='ls -l'
alias -- lla='ls -la'
alias -- lld='ls -ld'
alias -- llsd='cd ~/git/code/llama-stack'
alias -- llt='ls -lt'
alias -- lltS='ls -ltS'
alias -- lltc='ls -ltc'
alias -- lltu='ls -ltu'
alias -- lsd='ls -d */'
alias -- which='(alias; declare -f) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot'
alias -- wp='warp-terminal'
alias -- xzegrep='xzegrep --color=auto'
alias -- xzfgrep='xzfgrep --color=auto'
alias -- xzgrep='xzgrep --color=auto'
alias -- zegrep='zegrep --color=auto'
alias -- zfgrep='zfgrep --color=auto'
alias -- zgrep='zgrep --color=auto'
# Check for rg availability
if ! command -v rg >/dev/null 2>&1; then
  alias rg='/usr/bin/rg'
fi
export PATH=/home/skamenan/.pyenv/plugins/pyenv-virtualenv/shims\:/home/skamenan/.pyenv/shims\:/home/skamenan/.pyenv/bin\:/home/skamenan/.npm-global/bin\:/home/skamenan/.pyenv/plugins/pyenv-virtualenv/shims\:/home/skamenan/.pyenv/bin\:/home/skamenan/.npm-global/bin\:/tmp/.mount_Cursordbeh2u/usr/bin/\:/tmp/.mount_Cursordbeh2u/usr/sbin/\:/tmp/.mount_Cursordbeh2u/usr/games/\:/tmp/.mount_Cursordbeh2u/bin/\:/tmp/.mount_Cursordbeh2u/sbin/\:/tmp/.mount_cur5odc89/usr/bin/\:/tmp/.mount_cur5odc89/usr/sbin/\:/tmp/.mount_cur5odc89/usr/games/\:/tmp/.mount_cur5odc89/bin/\:/tmp/.mount_cur5odc89/sbin/\:/home/skamenan/.pyenv/plugins/pyenv-virtualenv/shims\:/home/skamenan/.pyenv/bin\:/home/skamenan/.npm-global/bin\:/home/skamenan/.pyenv/plugins/pyenv-virtualenv/shims\:/home/skamenan/.pyenv/bin\:/home/skamenan/.npm-global/bin\:/home/skamenan/.local/bin\:/home/skamenan/bin\:/usr/local/sbin\:/usr/local/bin\:/usr/sbin\:/usr/bin\:/home/skamenan/.npm-global/bin\:/home/skamenan/.npm-global/bin\:/home/skamenan/.npm-global/bin\:/home/skamenan/.cursor/extensions/ms-python.debugpy-2025.8.0-linux-x64/bundled/scripts/noConfigScripts\:/home/skamenan/.npm-global/bin
